/*
 * One real day of operator input, sanitized: 2026-09-23 (Europe/Kyiv), the day
 * the daily paid report and the Activity page disagreed by three hours
 * (docs/design/worktime-matches-zvit.md). It was replayed from a copy of the
 * activity store through `readHumanInputs` and kept only what the method
 * reads: each input's offset in seconds from the day's local midnight, its
 * project, its host, its surface and its kind. Projects are renamed `paid-a`,
 * `paid-b` (the two paid projects; B has no input this day) and `other-N`,
 * hosts `host-a` (the workstation) and `host-b` (the stage host). No id, hash
 * or text is kept.
 *
 * The page read the day as 5.5 h for paid-a and 11.5 h over every project;
 * the report counted 8.5 h for paid-a, with 01:00 and 02:00 a full hour each.
 */

import type { RequestKind, Surface } from "./method";

export const REPLAY_DAY = { date: "2026-09-23", tz: "Europe/Kyiv", start: Date.parse("2026-09-22T21:00:00Z") };

export const REPLAY_DAY_INPUTS: ReadonlyArray<readonly [offsetSec: number, project: string, host: string, surface: Surface, kind: RequestKind]> = [
  [517, "other-1", "host-a", "unknown", "message"],
  [552, "other-1", "host-a", "unknown", "message"],
  [641, "other-2", "host-a", "unknown", "message"],
  [1108, "paid-a", "host-b", "unknown", "message"],
  [1238, "paid-a", "host-b", "unknown", "message"],
  [2114, "paid-a", "host-b", "unknown", "message"],
  [2366, "paid-a", "host-b", "unknown", "message"],
  [2390, "paid-a", "host-b", "unknown", "message"],
  [2450, "paid-a", "host-b", "unknown", "message"],
  [2488, "paid-a", "host-b", "unknown", "message"],
  [2845, "other-1", "host-a", "unknown", "message"],
  [4158, "paid-a", "host-b", "unknown", "message"],
  [4718, "paid-a", "host-b", "unknown", "message"],
  [4998, "paid-a", "host-b", "unknown", "message"],
  [5071, "other-1", "host-a", "unknown", "message"],
  [5120, "other-1", "host-a", "unknown", "message"],
  [5224, "other-1", "host-a", "unknown", "message"],
  [5700, "paid-a", "host-b", "unknown", "message"],
  [5806, "other-1", "host-a", "unknown", "message"],
  [6001, "other-1", "host-a", "unknown", "message"],
  [6161, "paid-a", "host-b", "unknown", "message"],
  [6174, "paid-a", "host-b", "unknown", "message"],
  [6249, "other-1", "host-a", "unknown", "message"],
  [6276, "paid-a", "host-b", "unknown", "message"],
  [6648, "other-1", "host-a", "unknown", "message"],
  [6923, "other-1", "host-a", "unknown", "message"],
  [7151, "other-1", "host-a", "unknown", "message"],
  [7280, "paid-a", "host-b", "unknown", "message"],
  [7533, "paid-a", "host-b", "unknown", "message"],
  [7630, "paid-a", "host-b", "unknown", "message"],
  [7721, "paid-a", "host-b", "unknown", "message"],
  [8071, "other-1", "host-a", "unknown", "message"],
  [8239, "paid-a", "host-b", "unknown", "message"],
  [8334, "other-1", "host-a", "unknown", "message"],
  [8535, "other-3", "host-a", "unknown", "message"],
  [8621, "other-1", "host-a", "unknown", "message"],
  [8792, "other-3", "host-a", "unknown", "message"],
  [8852, "other-2", "host-a", "unknown", "message"],
  [8915, "paid-a", "host-b", "unknown", "message"],
  [8940, "paid-a", "host-b", "unknown", "message"],
  [9045, "other-2", "host-a", "unknown", "message"],
  [9667, "other-1", "host-a", "unknown", "message"],
  [9731, "other-1", "host-a", "unknown", "message"],
  [9858, "other-2", "host-a", "unknown", "message"],
  [10025, "other-1", "host-a", "unknown", "message"],
  [10288, "paid-a", "host-b", "unknown", "message"],
  [10416, "other-1", "host-a", "unknown", "message"],
  [10835, "paid-a", "host-b", "unknown", "message"],
  [10985, "paid-a", "host-b", "unknown", "message"],
  [11340, "paid-a", "host-b", "unknown", "message"],
  [11414, "paid-a", "host-b", "unknown", "message"],
  [11508, "paid-a", "host-b", "unknown", "message"],
  [11586, "paid-a", "host-b", "unknown", "message"],
  [11746, "paid-a", "host-b", "unknown", "message"],
  [11938, "paid-a", "host-b", "unknown", "message"],
  [12130, "other-4", "host-a", "terminal", "message"],
  [12198, "other-4", "host-a", "terminal", "message"],
  [12255, "other-4", "host-a", "terminal", "message"],
  [12316, "other-4", "host-a", "terminal", "message"],
  [12362, "other-1", "host-a", "unknown", "message"],
  [12367, "other-4", "host-a", "terminal", "message"],
  [25242, "other-1", "host-a", "unknown", "spawn"],
  [25491, "paid-a", "host-b", "unknown", "message"],
  [25609, "paid-a", "host-b", "unknown", "message"],
  [27138, "other-1", "host-a", "unknown", "message"],
  [27223, "paid-a", "host-b", "unknown", "message"],
  [27390, "paid-a", "host-b", "unknown", "message"],
  [28651, "paid-a", "host-b", "unknown", "message"],
  [29015, "paid-a", "host-b", "unknown", "message"],
  [30911, "other-1", "host-a", "unknown", "message"],
  [30998, "other-1", "host-a", "unknown", "message"],
  [31303, "other-1", "host-a", "unknown", "message"],
  [31450, "paid-a", "host-b", "unknown", "message"],
  [31583, "paid-a", "host-b", "unknown", "message"],
  [31620, "paid-a", "host-b", "unknown", "spawn"],
  [32738, "paid-a", "host-b", "unknown", "message"],
  [33116, "other-5", "host-b", "unknown", "message"],
  [34438, "other-1", "host-a", "unknown", "message"],
  [34660, "other-1", "host-a", "unknown", "message"],
  [35145, "other-4", "host-a", "unknown", "message"],
  [35307, "paid-a", "host-b", "unknown", "message"],
  [35796, "other-1", "host-a", "unknown", "message"],
  [35894, "other-1", "host-a", "unknown", "message"],
  [35957, "other-6", "host-a", "unknown", "message"],
  [36150, "paid-a", "host-b", "unknown", "message"],
  [36724, "other-6", "host-a", "unknown", "message"],
  [37022, "other-6", "host-a", "unknown", "message"],
  [37025, "other-2", "host-a", "unknown", "message"],
  [37523, "other-4", "host-a", "unknown", "message"],
  [39221, "paid-a", "host-b", "unknown", "message"],
  [39286, "paid-a", "host-b", "unknown", "message"],
  [39968, "paid-a", "host-b", "unknown", "message"],
  [44285, "other-1", "host-a", "unknown", "message"],
  [44300, "other-1", "host-a", "unknown", "message"],
  [44377, "other-3", "host-a", "unknown", "message"],
  [44676, "other-1", "host-a", "unknown", "message"],
  [45191, "other-1", "host-a", "unknown", "message"],
  [47133, "other-1", "host-a", "unknown", "message"],
  [47931, "paid-a", "host-b", "unknown", "message"],
  [48052, "other-1", "host-a", "unknown", "message"],
  [48985, "other-1", "host-a", "unknown", "message"],
  [55585, "other-1", "host-a", "unknown", "message"],
  [55967, "other-1", "host-a", "unknown", "message"],
  [56410, "other-1", "host-a", "unknown", "message"],
  [56470, "other-1", "host-a", "unknown", "message"],
  [58814, "other-1", "host-a", "unknown", "message"],
  [59274, "other-1", "host-a", "unknown", "message"],
  [60573, "other-1", "host-a", "unknown", "message"],
  [60611, "other-1", "host-a", "unknown", "message"],
  [60853, "other-1", "host-a", "unknown", "message"],
  [60885, "other-1", "host-a", "unknown", "message"],
  [61021, "other-3", "host-a", "unknown", "message"],
  [61529, "other-3", "host-a", "unknown", "message"],
  [64016, "paid-a", "host-b", "unknown", "message"],
  [64578, "paid-a", "host-b", "unknown", "message"],
  [64858, "other-4", "host-a", "terminal", "message"],
  [64872, "other-4", "host-a", "terminal", "message"],
  [65059, "paid-a", "host-b", "unknown", "message"],
  [65162, "paid-a", "host-b", "unknown", "message"],
  [65234, "other-1", "host-b", "unknown", "spawn"],
  [65270, "other-1", "host-b", "unknown", "message"],
  [65372, "other-4", "host-a", "terminal", "message"],
  [65746, "other-1", "host-b", "unknown", "message"],
  [66680, "other-1", "host-a", "unknown", "message"],
  [71864, "other-3", "host-a", "unknown", "message"],
  [72007, "other-3", "host-a", "unknown", "message"],
  [72304, "other-1", "host-b", "unknown", "message"],
  [73022, "paid-a", "host-b", "unknown", "message"],
  [75992, "other-3", "host-a", "unknown", "message"],
  [76240, "other-3", "host-a", "unknown", "message"],
  [76523, "paid-a", "host-b", "unknown", "message"],
  [80864, "paid-a", "host-b", "unknown", "message"],
  [81177, "other-3", "host-a", "unknown", "message"],
  [81737, "paid-a", "host-b", "unknown", "message"],
  [82482, "paid-a", "host-b", "unknown", "message"],
  [82547, "paid-a", "host-b", "unknown", "message"],
];
