/* Writes src/lib/team/confusables.ts from the Unicode confusables data
   (UTS #39): for every character that draws like another, the characters its
   skeleton maps to. Member names are compared by that skeleton, so a name
   spelt with look-alike letters collides with the one it imitates. Pass the
   path of a downloaded confusables.txt, or nothing to fetch the pinned
   version. */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const VERSION = "18.0.0";
const SOURCE = `https://www.unicode.org/Public/${VERSION}/security/confusables.txt`;

const file = process.argv[2];
const text = file
  ? readFileSync(file, "utf8")
  : await fetch(SOURCE, { signal: AbortSignal.timeout(30_000) }).then((response) => {
      if (!response.ok) throw new Error(`${SOURCE} answered ${response.status}`);
      return response.text();
    });
const version = /^# Version: (\S+)/m.exec(text)?.[1];
if (version !== VERSION) throw new Error(`expected confusables ${VERSION}, read ${version ?? "no version"}`);

/* One entry per line of the data: `SOURCE=TARGET[.TARGET…]` in hex. */
const entries: string[] = [];
for (const line of text.split("\n")) {
  const [source, target] = line.replace(/#.*/, "").split(";").map((field) => field.trim());
  if (!source || !target) continue;
  entries.push(`${source}=${target.split(/\s+/).join(".")}`);
}

/* Wrapped at about 100 characters, so a version bump reads as a diff of entries. */
const lines: string[] = [];
let current = "";
for (const entry of entries) {
  if (current && current.length + 1 + entry.length > 100) {
    lines.push(current);
    current = entry;
  } else {
    current = current ? `${current} ${entry}` : entry;
  }
}
if (current) lines.push(current);

const body = `/* Generated by \`bun scripts/generate-confusables.ts\` from the Unicode confusables data ${VERSION}
   (${SOURCE}). Do not edit by hand: regenerate to move the Unicode version. */

export const CONFUSABLES_VERSION = "${VERSION}";

/** \`SOURCE=TARGET[.TARGET…]\` in hex, whitespace-separated: the character on the left draws like the sequence on the right. */
export const CONFUSABLE_ENTRIES = \`
${lines.join("\n")}
\`;
`;

writeFileSync(path.join(process.cwd(), "src/lib/team/confusables.ts"), body);
console.log(`wrote ${entries.length} confusables from ${VERSION}`);
