/* Writes src/lib/tasks/lucideIconNames.ts from the installed lucide-react
   (#2102): every icon name a task may carry, and the older names lucide still
   accepts for renamed icons. Run it after moving the lucide-react version;
   the name-list test in taskIcon.test.ts fails while the committed list and
   the package disagree. */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { parseLucideIconImports } from "../src/lib/tasks/lucideIconSource";

const root = process.cwd();
const packageDir = path.join(root, "node_modules/lucide-react");
const { version } = JSON.parse(readFileSync(path.join(packageDir, "package.json"), "utf8")) as { version: string };
const { names, aliases } = parseLucideIconImports(readFileSync(path.join(packageDir, "dist/esm/dynamicIconImports.mjs"), "utf8"));

/* Wrapped at about 100 characters, so a version bump reads as a diff of names. */
function wrap(words: readonly string[]): string {
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    if (line && line.length + 1 + word.length > 100) {
      lines.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) lines.push(line);
  return lines.join("\n");
}

const body = `/* Generated by \`bun scripts/generate-lucide-icon-names.ts\` from lucide-react ${version} (#2102).
   Do not edit by hand: regenerate after moving the lucide-react version.
   The name-list test in taskIcon.test.ts fails while this list and the package disagree. */

export const LUCIDE_REACT_VERSION = "${version}";

/** Every icon name, kebab-case and whitespace-separated: the stored form of a task icon. */
export const LUCIDE_ICON_NAME_LIST = \`
${wrap(names)}
\`;

/** The names lucide keeps for renamed icons, as \`alias:name\` pairs. A task
    given one stores the name it points to. */
export const LUCIDE_ICON_ALIAS_LIST = \`
${wrap([...aliases].map(([alias, name]) => `${alias}:${name}`))}
\`;
`;

const target = path.join(root, "src/lib/tasks/lucideIconNames.ts");
writeFileSync(target, body);
console.log(`Wrote ${path.relative(root, target)}: ${names.length} names, ${aliases.size} aliases (lucide-react ${version})`);
